# Generated by Django 3.2.6 on 2021-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=20)),
                ('mes', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=20)),
                ('quant', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
            ],
        ),
    ]
